# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ro-ck-et builds Robot
email: fw.help@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ro-ck-et has a simple wish - he wants to build a robot to look after himself.
  He is looking into the future, of himself in the old age. He will have become old
  and frail, unable to tend to his own basic needs. To him, depending on another human
  being to provide such end-of-life care is fraught with uncertainties and risks.
  He might not be smart enough to smart enough to create this robot by himself, but
  as an engineer, he wants to contribute in whatever way that he can.
  This is a record of his hobbyistic efforts.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: n.a.
github_username:  ro-ck-et

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
